### ISSUE TITLE
只有音码的词组如何顶功？

### ISSUE THREAD

**Issue by capedghost** [amorphobia/rime-jiandao#11]
cizu_raw.txt中所有词组都编了包含形码的全码，但是在转换成词典文件之后很多词组都去掉了形码。
顶功是需要形码音码交替输入来进行的，只有音码的词组如何顶功呢？还是说这种情况就无法顶功了，只能用空格或次选键上屏？

**Comment by amorphobia** [comment]
你好，键道的音码最长是4码，顶功是在lua脚本中判断的，音码长度达到4码后，下一个若依然是音码，则顶功上屏

**Comment by capedghost** [comment]
> 你好，键道的音码最长是4码，顶功是在lua脚本中判断的，音码长度达到4码后，下一个若依然是音码，则顶功上屏

哦，好吧，确实，键道的文档里把这种叫定长上屏，一时忘了。
我试用过一段时间的原版键道6，后来了解到您的方案后观察了一下您的词库，对于这种仅保留音码的词组编码方式很不理解。

有些词组只有音码，有些是包含部分形码的非全码，有些则是全码，我觉得这无疑加重了使用者的心智负担。
因为在打字时，我不确定是否需要输入形码，需要形码的词我也不确定是需要输入一个、两个还是三个形码。
当我打完音码，候选词出现我想要的词后，是否还有未打完的形码？如果补上形码，会仍然得到这个候选词，还是会空码？

**Comment by amorphobia** [comment]
据我所知，键道已经停止研发了，所以现有的特性应该已经固定下来了

如果想要实验改进键道的话，可以加入键道QQ群讨论：https://jq.qq.com/?_wv=1027&k=c1T3vOwc
