### ISSUE TITLE
单字 '呪'

### ISSUE THREAD

**Issue by welandx** [amorphobia/rime-jiandao#9]
希望能增加 '咒' 的异体字 '呪'
理由：
1. 冰呪龙，怪物猎人世界冰原的封面怪，词条见 [wiki](https://mhworld.kiranico.com/zh/monsters/J1pFn/bing-zhou-long)
2. 呪術廻戦

**Comment by amorphobia** [comment]
巧了，最近正在加异体字，下个提交会包含

**Comment by amorphobia** [comment]
已提交，但请注意

1. 「呪」字只有全码
2. 由于编码空间不足，单字不会包含繁体字，因此「術」没有，需要通过简繁转换出字
3. 由于每个人需求不同，词组部分建议自行维护，可自行加上「呪術廻戦」等词组
4. 近期不会发新版本，可使用 [action](https://github.com/amorphobia/rime-jiandao/actions/runs/7712778232) 生成的版本，或者自己生成
